name: Run on Ubuntu

on:
  push:
    branches:
      - main

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Update system and install packages
      - name: Update and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget tree

      # Step 3: Run a custom script
      - name: Run custom commands
        run: |
          echo "Running on Ubuntu"
          uname -a
          tree

      # Step 4: Test code (Python Example)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Python script
        run: |
          echo "print('Hello from Python')" > test.py
          python test.py
